# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cache_pb2 as cache__pb2


class CacheServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDomainIP = channel.unary_unary(
        '/CacheService/GetDomainIP',
        request_serializer=cache__pb2.DomainRequest.SerializeToString,
        response_deserializer=cache__pb2.DomainResponse.FromString,
        )


class CacheServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDomainIP(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CacheServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDomainIP': grpc.unary_unary_rpc_method_handler(
          servicer.GetDomainIP,
          request_deserializer=cache__pb2.DomainRequest.FromString,
          response_serializer=cache__pb2.DomainResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CacheService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
