# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cache.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x63\x61\x63he.proto\"\x1f\n\rDomainRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"\x1c\n\x0e\x44omainResponse\x12\n\n\x02ip\x18\x01 \x01(\t2>\n\x0c\x43\x61\x63heService\x12.\n\x0bGetDomainIP\x12\x0e.DomainRequest\x1a\x0f.DomainResponseb\x06proto3')
)




_DOMAINREQUEST = _descriptor.Descriptor(
  name='DomainRequest',
  full_name='DomainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='DomainRequest.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=46,
)


_DOMAINRESPONSE = _descriptor.Descriptor(
  name='DomainResponse',
  full_name='DomainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='DomainResponse.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['DomainRequest'] = _DOMAINREQUEST
DESCRIPTOR.message_types_by_name['DomainResponse'] = _DOMAINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DomainRequest = _reflection.GeneratedProtocolMessageType('DomainRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOMAINREQUEST,
  __module__ = 'cache_pb2'
  # @@protoc_insertion_point(class_scope:DomainRequest)
  ))
_sym_db.RegisterMessage(DomainRequest)

DomainResponse = _reflection.GeneratedProtocolMessageType('DomainResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOMAINRESPONSE,
  __module__ = 'cache_pb2'
  # @@protoc_insertion_point(class_scope:DomainResponse)
  ))
_sym_db.RegisterMessage(DomainResponse)



_CACHESERVICE = _descriptor.ServiceDescriptor(
  name='CacheService',
  full_name='CacheService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=78,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDomainIP',
    full_name='CacheService.GetDomainIP',
    index=0,
    containing_service=None,
    input_type=_DOMAINREQUEST,
    output_type=_DOMAINRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CACHESERVICE)

DESCRIPTOR.services_by_name['CacheService'] = _CACHESERVICE

# @@protoc_insertion_point(module_scope)
