version: '3.8'

services:
  api_grpc_server:
    build: .
    container_name: api_grpc_server
    ports:
      - "8000:8000" 
      - "50051:50051" 
    depends_on:
      - redis1
      - redis2
    command: ["python", "grpc_server.py", "app.py", "uvicorn app:app --reload"] 

  redis1:
    image: bitnami/redis:latest
    container_name: redis-server-1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY=512kb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    ports:
      - "6380:6379"

  redis2:
    image: bitnami/redis:latest
    container_name: redis-server-2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY=512kb
      - REDIS_MAXMEMORY_POLICY=allkeys-fifo
    ports:
      - "6381:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis1
      - redis2










  
